feat: initial commit
max-vassiliev/java-shareit pull request #2
Opened 2023-02-08 14:45 UTC by max-vassiliev

Основные изменения:
- подключена база данных;
- новая функциональность: бронирование вещей, комментарии.

2023-02-09 18:42 UTC, AnastasiyaFomkina requested changes
Привет! Отличная работа - ты огромный молодец. Оставила совсем немного комментариев для саморазвития 

Если будет желание, можно сделать: 
`Задание со звездочкой:`
Лучше стараться максимально декомпозировать большие методы на более мелкие логические составляющие, так код будет проще читать и тестировать в дальнейшем.
Предлагаю выделить общие части в сервисах и вынесли их в приватные методы. Вообще есть отличный ресурс, где можно почитать про рефакторинг кода и взять на заметку подходы по декомпозиции - [рефакторинг гуру](https://refactoring.guru/) (может не открываться без впн)

2023-02-09 18:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingStateDto.java
> +    public static BookingStateDto fromString(String string) {
🔥

2023-02-09 18:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static Booking toBookingCreate(BookingDto bookingDto, User booker, Item item) {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-02-09 18:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/error/model/ErrorResponse.java
> +    private String error;
Может быть `final`

2023-02-09 18:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void addComments(ItemDto itemDto) {
Можно вынести работу с комментариями в отдельный сервис. Так мы немного разгрузим этот большой класс, что сделает код более читаемым и тестируемым

2023-02-09 18:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void addComments(ItemDto itemDto) {
Можно вынести работу с комментариями в отдельный сервис. Так мы немного разгрузим этот большой класс, что сделает код более читаемым и тестируемым

2023-02-10 12:36 UTC, max-vassiliev commented
Спасибо за совет по декомпозиции! Изучу материал по ссылке. Пытался это сделать местами, где замечал дублирование кода. Подумаю, что еще можно сделать.

2023-02-10 14:16 UTC, AnastasiyaFomkina approved these changes

2023-02-10 15:35 UTC, merged