feat: add item requests and tests
max-vassiliev/java-shareit pull request #3
Opened 2023-03-03 16:15 UTC by max-vassiliev

**Новая функциональность**: запрос на добавление вещи.
**Рефакторинг**: пагинация к существующим запросам.
**Тесты**: добавлены тесты для всего приложения.

2023-03-04 15:01 UTC, AnastasiyaFomkina requested changes
Привет! Отличная работа, молодец, что написал такие развернутые тесты 🔥
Рефакторинг и новая функциональность - просто бомба
По тестам оставила немного предложений, давай попробуем избавиться от дублирующих проверок и немного подсократить повторяющийся код

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    ItemRepository itemRepository;
У многих параметров класс не хватает модификатора доступа, нужно добавить

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +class BookingRepositoryTest {
_Опционально_
Чтобы большие тесты было проще читать, можно их разбить на маленькие логические составляющие с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/)

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        assertEquals(bookings.get(2).getItem().getName(), outputDtos.get(2).getItem().getName());
Данная проверка повторяется в тесте выше на строках 425-446 и в тестах ниже, чтобы не дублировать код, ее можно вынести в отдельный метод. Так получится хорошо сократить код и сделать его более читаемым. 

Посмотри, пожалуйста, внимательно на тесты и попробуй выделить одинаковые проверки в отдельные методы

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerSpringBootTest.java
> +    Item item3;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/ItemControllerSpringBootTest.java
> +    Comment item1Comment;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/repository/CommentRepositoryTest.java
> +    Comment comment3;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    ItemRequest request2;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +    ObjectMapper mapper;
Не хватает модификатора доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestSpringBootTest.java
> +    User user3;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/request/repository/ItemRequestRepositoryTest.java
> +    User user3;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/user/UserSpringBootTest.java
> +    User user3;
Не хватает модификаторов доступа

2023-03-04 15:01 UTC, afomkina commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplTest.java
> +    UserServiceImpl userService;
Не хватает модификаторов доступа

2023-03-04 22:19 UTC, max-vassiliev commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +class BookingRepositoryTest {
Спасибо за совет и материал! Изучу, попробую сделать в следующем спринте — сейчас не хватает времени. И отдельное спасибо за всё ревью!

2023-03-05 09:43 UTC, AnastasiyaFomkina approved these changes

2023-03-20 16:10 UTC, merged