Initial commit
max-vassiliev/java-shareit pull request #4
Opened 2023-03-30 19:43 UTC by max-vassiliev

**Рефакторинг:**
- Приложение разбито на два микросервиса: `shareIt-server` и `shareIt-gateway`
- Обновлены методы получения бронирований в `BookingServiceImpl`

**Docker:**
- Добавлены `docker-compose.yml` и `Dockerfile` для каждого микросервиса

2023-03-31 10:47 UTC, AnastasiyaFomkina requested changes
Отлично получилось, молодец 🔥

2023-03-31 10:47 UTC, AnastasiyaFomkina commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Лучше удалить закомментированные значения

2023-03-31 10:47 UTC, AnastasiyaFomkina commented on gateway/src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +class UserControllerTest {
_Опционально_
Предлагаю немного подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2023-04-01 11:46 UTC, max-vassiliev commented on gateway/src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +class UserControllerTest {
Попробовал сделать это в классе UserControllerTest. Надеюсь, правильно понял идею.

2023-04-01 13:09 UTC, AnastasiyaFomkina approved these changes

2023-04-01 13:09 UTC, AnastasiyaFomkina commented on gateway/src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +class UserControllerTest {
Да, все верно сделал, молодец 👍

2023-04-03 16:44 UTC, merged